### ISSUE TITLE
Internet des Objets - Partie 1 - Auriles ( pour mercredi )

### ISSUE THREAD

**Issue by Auriles** [RobinChap/ProjTransCIO#1]
- Simulation de système embarqué sur VM Linux sans interface graphique.
- Ajouter un serveur ssh pour connexion à distance

**Comment by RobinChap** [comment]
Fait sur mon pc pour des expériences le vrais est chez david

**Comment by Auriles** [comment]
Copie de la VM sur chaque PC ( demain )
